name = "vantage-landscaping"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "CHAT_KV"
id = "0c4014e70c0848899e2a32e0ec53dcc4"

[[kv_namespaces]]
binding = "SMS_KV"
id = "ebe309f4da7c4c44a7ba4af9757f1670"
